apiVersion: v2
name: rill-flow
version: 0.0.5
description: rill flow orchestration engine
keywords:
  - rill flow
  - orchestration
home: https://weibocom.github.io/rill-flow
sources:
  - https://github.io/weibocom/rill-flow
maintainers: 
  - name: axb
    url: https://github.com/qdaxb
dependencies:
  - name: common
    version: 2.13.3
    repository: https://charts.bitnami.com/bitnami
  - name: jaeger
    version: 0.72.1
    repository: https://jaegertracing.github.io/helm-charts/
    condition: jaeger.enabled
  - name: redis
    version: 18.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
