## Rill Flow helm chart 参数说明


## Rill Flow 单机部署依赖组件参数配置
## Redis启动配置
## @param redis.architecture  Redis部署模式: `standalone`（单例模式） or `replication`（主从模式），默认为`standalone`
## @param redis.enable 部署Rill Flow服务是否启动redis，默认为`true`：默认启动redis
## @param redis.auth.enabled redis启动是否开启密码认证，默认为`false`:不开启密码认证
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

## Jaeger Trace启动配置
## @param jaeger.enabled 部署Rill Flow 是否启动jaeger组件，默认为`true`：默认启动jaeger组件
## @param jaeger.allInOne.enabled 部署jaeger服务一键启动Jaeger UI, collector, query, 和 agent 组件，默认为`true`
## @param jaeger.query.enabled 部署jaeger服务是否单独启动query组件, 默认为`false`
## @param jaeger.agent.enabled 部署jaeger服务是否单独启动agent组件, 默认为`false`
## @param jaeger.collector.enabled 部署jaeger服务是否单独启动collector组件, 默认为`false`
jaeger:
  enabled: true
  allInOne:
    enabled: true
  query:
    enabled: false
  agent:
    enabled: false
  collector:
    enabled: false
  cassandra:
    config:
      size: 1
      cluster_size: 1

## Rill Flow 服务启动配置
## @param rillFlow.backend.env.rillFlowDescriptorRedisHost 储存流程图(DAG)信息的redis地址，默认为redis组件的k8s service地址
## @param rillFlow.backend.env.rillFlowDescriptorRedisPort 储存流程图(DAG)信息的redis端口，默认为`6379`
## @param rillFlow.backend.env.rillFlowDefaultRedisHost 储存Rill Flow 其他信息的redis地址，默认为redis组件的k8s service地址
## @param rillFlow.backend.env.rillFlowDefaultRedisPort 储存Rill Flow 其他信息的redis端口，默认为`6379`
## @param rillFlow.backend.env.rillFlowTraceEndpoint trace数据采集器地址，默认为jaeger collector组件的k8s service地址
## @param rillFlow.backend.env.rillFlowDagRedoUrl 流程重做接口地址，默认为Rill Flow后端服务的k8s service地址
## @param rillFlow.backend.env.rillFlowCallbackUrl 任务节点执行结果回调通知接口地址，默认为Rill Flow后端服务的k8s service地址
## @param rillFlow.ui.backendServer Rill Flow后端服务地址，供前端页面调用使用，默认为Rill Flow后端服务的k8s service地址
## @param rillFlow.ui.traceServer Rill Flow trace查询服务地址，供前端页面调用使用，默认为jaeger query组件的k8s service地址
global:
  imageRegistry: docker.io
rillFlow:
  backend:
    image:
      repository: weibocom/rill-flow
      tag: 0.1.0
      digest: ""
    env:
      rillFlowDescriptorRedisHost: "rill-flow-redis-master.rill-flow"
      rillFlowDescriptorRedisPort: "6379"
      rillFlowDefaultRedisHost: "rill-flow-redis-master.rill-flow"
      rillFlowDefaultRedisPort: "6379"
      rillFlowTraceEndpoint: "http://rill-flow-jaeger-collector:4317"
      rillFlowDagRedoUrl: "http://rill-flow-service:8080/flow/redo.json"
      rillFlowCallbackUrl: "http://rill-flow-service:8080/flow/finish.json"
  ui:
    image:
      repository: weibocom/rill-flow-ui
      tag: 0.1.0
      digest: ""
    backendServer: "http://rill-flow-service:8080"
    traceServer: "http://rill-flow-jaeger-query:16686"
