---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rill-flow-ui
  namespace: {{ .Release.Namespace }}
  labels:
    rill-flow-ui: rill-flow-ui
spec:
  selector:
    matchLabels:
      rill-flow-ui: rill-flow-ui
  template:
    metadata:
      labels:
        rill-flow-ui: rill-flow-ui
    spec:
      containers:
        - name: rill-flow-ui
          image: {{ include "common.images.image" (dict "imageRoot" .Values.rillFlow.ui.image "global" .Values.global)}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BACKEND_SERVER
              value: {{ .Values.rillFlow.ui.backendServer}}
            - name: TRACE_SERVER
              value: {{ .Values.rillFlow.ui.traceServer}}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
